[features]
seeds = false
skip-lint = false
[programs.localnet]
wba_vault = "EzdvFHcekYLwsqmZqADXwN6mv4BWea5aEdBojY5359rZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/home/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
