[features]
seeds = false
skip-lint = false
[programs.localnet]
escrow = "7b69427tSXuZH9TsB6oT2i7vvkxrqxPa8WNhSdYrFeNx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/home/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
